######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 17 11:02:08 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT+=opengl



# Input
HEADERS += GLWidget.h Window.h CoordWidget.h
SOURCES += GLWidget.cpp main.cpp Window.cpp bmploader.cpp CoordWidget.cpp
